<?php

// Reuse the main application config so all directory constants (DIR_SYSTEM,
// DIR_APPLICATION, etc.) are defined exactly as in production.
require_once __DIR__ . '/../public/config.php';

// Load core engine classes used by controllers in tests.
require_once DIR_SYSTEM . 'engine/registry.php';
require_once DIR_SYSTEM . 'engine/controller.php';

// Path to the public API controllers used in tests (v1 public API).
define('PUBLIC_API', DIR_APPLICATION . 'controller/publicapi/v1/');

define('SKIP_INTEGRATION_TESTS', true);
define('SIGNING_TEST_USER2_BEARER_TOKEN', 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2cWhLOVF2Wnk0a1JzMk5iOUhWWkpjenFLdjl5cVJSVGQyOTNZUldOY1BJIn0.eyJleHAiOjE3NzM5NDA3MzQsImlhdCI6MTc3MzkwNDczNSwiYXV0aF90aW1lIjoxNzczOTA0NzM0LCJqdGkiOiJvbnJ0YWM6MzliYmZjM2UtNTE0Ni02NjlhLWQwNjUtMDQ4NGJlNjJkY2EwIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmRldi5zaW1wbGlmaS5yby9yZWFsbXMvU2ltcGxpZmkiLCJhdWQiOlsic2ltcGxpZmktYmFja2VuZCIsImFjY291bnQiXSwic3ViIjoiN2MyYjI5ZDYtYzk2Yi00Y2M0LWE4OWUtYjUyNzEwODQyZjUyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2ltcGxpZmktZnJvbnRlbmQiLCJzaWQiOiJEdnpYZ1pXZ2lhNF9nN3JxVDFVZWx1RlEiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImh0dHBzOi8vYXBwLnNpbXBsaWZpLnJvIiwiaHR0cHM6Ly9hcHAuZHIuc2ltcGxpZmkucm8iLCJodHRwczovL2FwcDAxLmRldi5zaW1wbGlmaS5ybyIsImh0dHBzOi8vYXBwLmRldi5zaW1wbGlmaS5ybyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc2ltcGxpZmkiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiQWxleCBaYW1maXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbGV4YW5kcnUuemFtZmlyK3Rlc3RAc2ltcGxpZmkucm8iLCJsb2NhbGUiOiJlbiIsImdpdmVuX25hbWUiOiJBbGV4IiwiZmFtaWx5X25hbWUiOiJaYW1maXIiLCJlbWFpbCI6ImFsZXhhbmRydS56YW1maXIrdGVzdEBzaW1wbGlmaS5ybyJ9.WttJzgnQZuySbjKtTeds2EfxGVKSlrLEI-SE5cj60271TIg74bzWTX6m3XVJT3IPFoWpa_cX9Dt9Iyb372EwjqLqj-TzY7dm7Ody6rj15BXokq09FSzKA0rQqSBOjL4p_UVSgtf0Tlurbs61J02q-LYlKhIlRCL1FlRmSwFHcIJQtqoSDN0wG43Ulf7z9aaIMD2NXhVY_pn3qkPQJqlbnfaHe-QX1MhXc_QhDtq5vN37vqzVPghMt46zHmp5Z59kgNoYfIRXdnEgu2h7Odg_s4QYtisJSm4KR3f0QBs83_Jp_2XkXaDEkE8uOQ0V54DhwHOmQHLVOxQGF62NFCMzqA');